#include "UI_Graph.h"

DashboardScreen dashboardScreen;
OperatorMenuScreen operatorMenuScreen;
CompactionMenuScreen compactionMenuScreen;
PinEntryScreen pinEntryScreen;
EngineerMenuScreen engineerMenuScreen;
ConfigEditorScreen configEditorScreen;
RemoteSettingsScreen remoteSettingsScreen;
ErrorsScreen errorsScreen;
UnloadPalletsScreen unloadPalletsScreen;
StatsScreen statsScreen;
DebugInfoScreen debugInfoScreen;
MovementScreen movementScreen;
MovementAxisScreen movementAxisScreen;